# Generated by Django 6.0 on 2026-05-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_assign',
            name='employe_id',
        ),
    ]
