# Generated by Django 6.0 on 2026-05-04 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_task_assign_employe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('manager_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.manegr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myprofile')),
            ],
        ),
    ]
